name: AWS IP Rest Workflow
on:
  push:
  pull_request:
jobs:
  build:
    name: Backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Run Tests
        run: .\gradlew test

      - name: Build Project
        run: .\gradlew assemble
